"use client"

import { useState } from "react"
import { Check, Eye, LockKeyhole, RotateCcw, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useLocalStorage } from "@/lib/use-local-storage"
const grounding=[{n:5,s:"things you can see"},{n:4,s:"things you can feel"},{n:3,s:"things you can hear"},{n:2,s:"things you can smell"},{n:1,s:"thing you can taste"}]
export function AnxietyToolkit(){const [step,setStep]=useState(0);const [done,setDone]=useState(false);const [worry,setWorry]=useLocalStorage("wakeupsmart-worry","")
 return <section id="anxiety" className="mx-auto max-w-6xl px-5 py-20"><div className="mb-10 flex flex-col gap-3"><p className="text-sm font-medium text-primary">ANXIETY TOOLKIT</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">Come back to right now.</h2><p className="max-w-xl leading-relaxed text-muted-foreground">Simple grounding for racing thoughts. Take what helps and leave the rest.</p></div><div className="grid gap-5 lg:grid-cols-2"><div className="glass flex min-h-96 flex-col justify-between rounded-3xl p-6 sm:p-8"><div><Eye className="size-6 text-primary"/><p className="mt-8 text-sm text-muted-foreground">5–4–3–2–1 grounding</p>{done?<><h3 className="mt-3 text-3xl font-medium">You’re here.</h3><p className="mt-3 leading-relaxed text-muted-foreground">Notice one slow breath. You don’t have to solve everything tonight.</p></>:<><h3 aria-live="polite" className="mt-3 text-3xl font-medium">Name {grounding[step].n}{" "}{grounding[step].s}</h3><p className="mt-3 leading-relaxed text-muted-foreground">Look around slowly. Say each one quietly or simply notice it.</p></>}</div><div className="mt-8 flex gap-3">{done?<Button onClick={()=>{setStep(0);setDone(false)}} className="rounded-full"><RotateCcw data-icon="inline-start"/>Start again</Button>:<><Button onClick={()=>step===4?setDone(true):setStep(step+1)} className="rounded-full"><Check data-icon="inline-start"/>I noticed them</Button>{step>0&&<Button variant="outline" onClick={()=>setStep(step-1)} className="rounded-full">Back</Button>}</>}</div></div>
 <div className="glass flex min-h-96 flex-col rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Worry dump</p><h3 className="mt-2 text-2xl font-medium">Put it down for tonight.</h3></div><LockKeyhole className="size-5 text-primary"/></div><textarea value={worry} onChange={e=>setWorry(e.target.value)} placeholder="Write without editing. This stays only in your browser..." className="mt-6 min-h-48 flex-1 resize-none rounded-2xl border border-border bg-background/40 p-4 leading-relaxed outline-none focus:border-primary"/><div className="mt-4 flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">Autosaved privately</p><Button variant="outline" onClick={()=>setWorry("")} className="rounded-full"><Trash2 data-icon="inline-start"/>Release it</Button></div></div></div></section> }
