"use client"

import { useEffect, useState } from "react"
import { BookOpen, Pause, Play, ScanLine } from "lucide-react"
import { Button } from "@/components/ui/button"

const sessions = {
  story: ["Settle into the quiet", "Imagine a lantern beside a still lake", "Watch the water carry the day away", "The path home is soft and familiar", "You are safe to rest now"],
  scan: ["Notice the weight of your head", "Soften your jaw and shoulders", "Let your breath move through your chest", "Release your belly, hips, and legs", "Feel your whole body supported"],
}
export function GuidedRest(){ const [type,setType]=useState<keyof typeof sessions>("story"); const [step,setStep]=useState(0); const [playing,setPlaying]=useState(false)
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(s=>{if(s>=sessions[type].length-1){setPlaying(false);return s}return s+1}),7000);return()=>clearInterval(id)},[playing,type])
 const choose=(next:keyof typeof sessions)=>{setType(next);setStep(0);setPlaying(false)}
 return <section id="rest" className="mx-auto max-w-6xl px-5 py-20"><div className="mb-10 flex flex-col gap-3"><p className="text-sm font-medium text-primary">GUIDED REST</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">A softer place for your attention.</h2></div><div className="grid gap-5 md:grid-cols-[.75fr_1.25fr]"><div className="flex flex-col gap-3"><button onClick={()=>choose("story")} className={`rounded-3xl border p-6 text-left transition-colors ${type==="story"?"border-primary bg-primary/10":"border-border bg-card/40"}`}><BookOpen className="mb-8 size-6 text-primary"/><h3 className="text-xl font-medium">The Lantern Lake</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A five-minute sleep story for letting go.</p></button><button onClick={()=>choose("scan")} className={`rounded-3xl border p-6 text-left transition-colors ${type==="scan"?"border-primary bg-primary/10":"border-border bg-card/40"}`}><ScanLine className="mb-8 size-6 text-primary"/><h3 className="text-xl font-medium">Body Scan</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Release tension from head to toe.</p></button></div><div className="glass flex min-h-96 flex-col justify-between rounded-3xl p-7 sm:p-10"><div><p className="text-sm text-muted-foreground">Step {step+1} of {sessions[type].length}</p><p aria-live="polite" className="mt-10 max-w-xl text-balance text-3xl font-medium leading-relaxed sm:text-4xl">{sessions[type][step]}</p></div><div><div className="mb-5 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all duration-700" style={{width:`${((step+1)/sessions[type].length)*100}%`}}/></div><div className="flex gap-3"><Button onClick={()=>setPlaying(!playing)} className="rounded-full">{playing?<Pause data-icon="inline-start"/>:<Play data-icon="inline-start"/>}{playing?"Pause":"Begin"}</Button><Button variant="outline" onClick={()=>{setStep(0);setPlaying(false)}} className="rounded-full">Restart</Button></div></div></div></div></section> }
