"use client"

import { BookText, Flame, Lightbulb, Moon, Smartphone, SunMedium } from "lucide-react"
import { useEffect } from "react"
import { Button } from "@/components/ui/button"
import { useLocalStorage } from "@/lib/use-local-storage"
const tips=[{icon:SunMedium,title:"Anchor your morning",text:"Wake within the same 30-minute window, even after a difficult night."},{icon:Smartphone,title:"Dim the inputs",text:"Lower light and stimulating content during the final hour before bed."},{icon:Moon,title:"Cool and quiet",text:"A slightly cooler, darker room supports your natural temperature drop."}]
export function SleepInsights(){const [reader,setReader]=useLocalStorage("wakeupsmart-reader",false);useEffect(()=>{document.documentElement.classList.toggle("reader",reader);return()=>document.documentElement.classList.remove("reader")},[reader])
return <section id="tips" className="mx-auto max-w-6xl px-5 py-20"><div className="glass rounded-3xl p-6 sm:p-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-sm font-medium text-primary">GENTLE SLEEP TIPS</p><h2 className="mt-3 text-balance text-3xl font-semibold tracking-tight">Small rituals, repeated softly.</h2></div><Button variant="outline" onClick={()=>setReader(!reader)} className="w-fit rounded-full"><BookText data-icon="inline-start"/>{reader?"Standard view":"Dark reader mode"}</Button></div><div className="mt-10 grid gap-4 md:grid-cols-3">{tips.map(t=><article key={t.title} className="rounded-2xl bg-secondary/50 p-5"><t.icon className="size-5 text-primary"/><h3 className="mt-6 font-medium">{t.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{t.text}</p></article>)}</div><p className="mt-8 flex items-start gap-2 text-xs leading-relaxed text-muted-foreground"><Lightbulb className="mt-0.5 size-4 shrink-0"/>WakeUpSmart offers general wellness guidance, not medical care. If sleep or anxiety regularly affects daily life, consider speaking with a qualified professional.</p></div></section>}
